camunda:
  client:
    mode: self-managed
    prefer-rest-over-grpc: false
    rest-address: http://localhost:8080
    grpc-address: http://localhost:26500
    enabled: true
    auth:
      method: none