name: Pre-Merge Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v6

      # Step 2: Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      # Step 3: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 4: Run Gradle build
      - name: Run Gradle Build
        run: ./gradlew build
